### ISSUE TITLE
Some results do not display?

### ISSUE THREAD

**Issue by silent** [BetterOffGone/Discord-Webhook-IP-Logger#2]
Currently, I have this setup on my website and it doesn't display the following information within the webhook.
ISP:
Location:
Region: 
Country 
Postal Code: 

Is there anything I can do to fix that?

**Comment by BetterOffGone** [comment]
Hello, can you provide screenshots of this please so I can improve this code :)

**Comment by silent** [comment]
Mate, this was like last month lmfao. I found this and I like the way it posts the results: https://github.com/TheBinaryDaemon/Webhook-IP-Logger
